### ISSUE TITLE
Bump dependency github.com/lestrrat-go/jwx from v1.2.26 to v1.2.28

### ISSUE THREAD

**Issue by omar-scio** [okta/okta-jwt-verifier-golang#109]
The authors of jwx say in their v1.2.28 release notes [here](https://github.com/lestrrat-go/jwx/releases/tag/v1.2.28) that there was a security bug patched:
>v1.2.28 09 Jan 2024
[Security Fixes]
>  * [jws] JWS messages formated in full JSON format (i.e. not the compact format, which
    consists of three base64 strings concatenated with a '.') with missing "protected"
    headers could cause a panic, thereby introducing a possiblity of a DoS.
>
>    This has been fixed so that the `jws.Parse` function succeeds in parsing a JWS message
    lacking a protected header. Calling `jws.Verify` on this same JWS message will result
    in a failed verification attempt. Note that this behavior will differ slightly when
    parsing JWS messages in compact form, which result in an error.

Can the maintainers of this library please update this dependency?

**Comment by lhopcroft123** [comment]
Note there was also a security issue fixed in [v1.2.27](https://github.com/lestrrat-go/jwx/releases/tag/v1.2.27) so there are currently 2 CVEs present in this code due to dependency on v1.2.26:

- [CVE-2024-21664 (High)](https://nvd.nist.gov/vuln/detail/CVE-2024-21664) fixed in v1.2.28
- [CVE-2023-49290 (Medium)](https://nvd.nist.gov/vuln/detail/CVE-2023-49290) fixed in v1.2.27

As a workaround until this is fixed, you can add the following to your `go.mod` file to force use of v1.2.28 instead of v1.2.26:

```
replace github.com/lestrrat-go/jwx v1.2.26 => github.com/lestrrat-go/jwx v1.2.28
```
