### ISSUE TITLE
Add ability to validate for a slice of CIDs

### ISSUE THREAD

**Issue by MartinLeedotOrg** [okta/okta-jwt-verifier-golang#15]
Happy to make a PR for this if it's sensible.

I have an API that's accessed either through a webapp or through API tokens issued as Client IDs and Client Secrets from Okta.

I would like to validate the CID is any one of the CIDs that my access policy allows.

**Comment by CarlosPadilla** [comment]
This can be addressed using a comma-separated string in order to avoid changing the type of the ClaimsToValidate map[string]string property
[comma separated proposal](https://play.golang.org/p/9dY-9Qx-PKM)

Or we can change the type to match both sides, but that way we have to add type switch validation to each property on setup
[type assertion propossal](https://play.golang.org/p/wgMNwat4eU7)

what do you think about these proposals, I would be happy to make a new PR or add this to my current PR

**Comment by bretterer** [comment]
Will be resolved by #54
