### ISSUE TITLE
JwtVerifier.getMetadata() builds invalid url

### ISSUE THREAD

**Issue by zetsub0u** [okta/okta-jwt-verifier-golang#47]
Hello, i used the lib with a dev environment and everything was fine, once i tried to use our corporate account things started to panic inside the lib.

What i'm seeing is that the metadata url created is valid for dev account but not for paid ones...
`metaDataUrl := j.Issuer + j.Discovery.GetWellKnownUrl()`

the issuer url for a dev accont would be `.../oauth2/default/.wellknwon...etc` while for our company url it would be `../oauth/.wellknown...etc`, the later doesn't exist, it 404s and it doesnt fail, the metadata map doesnt get populated and ends up panicking later on while trying to cast an empty map content to a string.

**Comment by bretterer** [comment]
Hi, thank you for your feedback here.  I am a little confused where the issue here is.

`GetWellKnownUrl` will return `Issuer + "/.well-known/openid-configuration"

So, you would want to set your Issuer to be whatever is infront of the `/.well-known....`

If you need to have custom discovery for metadata, you can created your own discovery package by following the `discovery/oidc/oidc.go` file as a template.

Does this help?
